version: 2

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        # Lint the source code
      - run: npm run lint
        # Test the source code
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10-browsers
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm set registry http://wmnexusec2.topcoder-dev.com/repository/hello-world-jaydesai/
      - run: echo "//wmnexusec2.topcoder-dev.com/repository/hello-world-jaydesai/:auth=dG9wY29kZXJkZXY6VG9wY29kZXIxMjMh" > ~/repo/.npmrc

      - run: npm publish
workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
